### ISSUE TITLE
Cannot import package

### ISSUE THREAD

**Issue by mwojnowicz** [madeleineudell/ParallelSparseMatMul.jl#13]
I have successfully cloned the ParallelSparseMatMul package, but I get an error when I import it.

julia> Pkg.clone("git@github.com:madeleineudell/ParallelSparseMatMul.jl.git")
INFO: Cloning ParallelSparseMatMul from git@github.com:madeleineudell/ParallelSparseMatMul.jl.git
INFO: Computing changes...
INFO: No packages to install, update or remove
INFO: Package database updated

julia> using ParallelSparseMatMul
ERROR: error in method definition: function SparseMatrix.SparseMatrixCSC must be explicitly imported to be extended
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/mwojnowicz/.julia/v0.3/ParallelSparseMatMul/src/parallel_matmul.jl, in expression starting on line 151
while loading /home/mwojnowicz/.julia/v0.3/ParallelSparseMatMul/src/ParallelSparseMatMul.jl, in expression starting on line 13

julia> versioninfo()
Julia Version 0.3.8-pre+22
Commit 5078421* (2015-04-28 09:05 UTC)
Platform Info:
  System: Linux (x86_64-amazon-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.3

**Comment by madeleineudell** [comment]
It should work now; I just modified the package to explicitly import `SparseMatrixCSC`.
